### ISSUE TITLE
Failed build when running locally

### ISSUE THREAD

**Issue by algoritmau** [apple/swift-org-website#347]
## Describe the bug

I'm unable to get the project up and running due to an error when following the instructions as-is.

## To Reproduce

1. Open the Terminal
2. Execute:
```bash
git clone https://github.com/apple/swift-org-website.git
cd swift-org-website
bundle install
LC_ALL=en_us.UTF-8 bundle exec jekyll serve
open "http://localhost:4000"
```
3. See error

## Expected behavior

The project is up and running and served via `http://localhost:4000`

## Actual behavior

The following error is thrown:

```bash
# ...
Using terminal-table 2.0.0
Using jekyll 4.2.2
Using jekyll-redirect-from 0.16.0
Using webrick 1.7.0
Bundle complete! 3 Gemfile dependencies, 30 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Configuration file: /Users/<username>/programming/swift/playground/swift-org-website/_config.yml
            Source: /Users/<username>/programming/swift/playground/swift-org-website
       Destination: /Users/<username>/programming/swift/playground/swift-org-website/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
Liquid Exception: undefined method `tainted?' for "The Swift.org Blog":String in /Users/<username>/programming/swift/playground/swift-org-website/_layouts/post.html
                    ------------------------------------------------
      Jekyll 4.2.2   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
/opt/homebrew/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/variable.rb:124:in `taint_check': undefined method `tainted?' for "The Swift.org Blog":String (NoMethodError)

      return unless obj.tainted?
                       ^^^^^^^^^
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/variable.rb:89:in `render'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:80:in `render'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:131:in `render_liquid'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:194:in `render_layout'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:163:in `place_in_layouts'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:93:in `render_document'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:63:in `run'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:547:in `render_regenerated'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:532:in `block (2 levels) in render_docs'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:531:in `each'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:531:in `block in render_docs'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:530:in `each_value'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:530:in `render_docs'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:210:in `render'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:80:in `process'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:28:in `process_site'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:65:in `build'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:36:in `process'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `each'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.2.0/bin/jekyll:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.2.0/bin/jekyll:25:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:58:in `load'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.3.13/lib/bundler/cli.rb:483:in `exec'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.3.13/lib/bundler/cli.rb:31:in `dispatch'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.3.13/lib/bundler/cli.rb:25:in `start'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.3.13/exe/bundle:48:in `block in <top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.3.13/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.3.13/exe/bundle:36:in `<top (required)>'
	from /opt/homebrew/opt/ruby/bin/bundle:25:in `load'
	from /opt/homebrew/opt/ruby/bin/bundle:25:in `<main>'
```

## Screenshots

<img width="1221" alt="Screenshot 2023-07-24 at 8 27 21 PM" src="https://github.com/apple/swift-org-website/assets/49292621/e8f25f84-4537-410c-a335-7fa647a6b09c">

### OS (please complete the following information):

- macOS
- Version: 13.4 (22F66)
- Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
- Target: arm64-apple-macosx13.0
- ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]

### Swift.org version/commit hash

commit 8ed8ac5ad1fb1b36fcf6912d5783fce87433342f

**Comment by 0xTim** [comment]
This is probably an issue with Ruby 3.2 as the Dockerfile and compose file work fine using 3.1. It might be a case of just updating Jekyll but someone with more Ruby knowledge may have to jump in as we've had issues 'just' upgrading in the past

**Comment by daveverwer** [comment]
Thanks for reporting this, @patternina. I just opened #349 to fix it.

In the mean time, while we wait for that to merge, if you'd like a workaround then the easiest way is to install [`rbenv`](https://github.com/rbenv/rbenv). The `.ruby-version` file in the repository will tell `rbenv` which version of Ruby to install. The easiest way to install `rbenv` is with Homebrew. That's also how I have it installed.

You can run the site of the current `main` branch with Ruby 3.1 by installing `rbenv` and then running the following commands in the directory:

```
cd /path/to/swift-org-website
rbenv install
bundle install
LC_ALL=en_us.UTF-8 bundle exec jekyll serve
open "http://localhost:4000"
```

Running `rbenv install` without a version number installs whatever version is specified in `.ruby-version`.

Hope this helps!

**Comment by linhaosunny** [comment]
> Thanks for reporting this, @patternina. I just opened #349 to fix it.
> 
> In the mean time, while we wait for that to merge, if you'd like a workaround then the easiest way is to install [`rbenv`](https://github.com/rbenv/rbenv). The `.ruby-version` file in the repository will tell `rbenv` which version of Ruby to install. The easiest way to install `rbenv` is with Homebrew. That's also how I have it installed.
> 
> You can run the site of the current `main` branch with Ruby 3.1 by installing `rbenv` and then running the following commands in the directory:
> 
> ```
> cd /path/to/swift-org-website
> rbenv install
> bundle install
> LC_ALL=en_us.UTF-8 bundle exec jekyll serve
> open "http://localhost:4000"
> ```
> 
> Running `rbenv install` without a version number installs whatever version is specified in `.ruby-version`.
> 
> Hope this helps!

I got the same issue, thks a lot!

**Comment by daveverwer** [comment]
> I got the same issue, thks a lot!

Could you elaborate a little on the issue you're facing please @linhaosunny. This original issue should now be fixed.
